spring:
  datasource:
    url: jdbc:h2:file:./data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL_QUERY:false}

app:
  tepResources: classpath:tep/*
  paypalResources: classpath:paypal/*
  vectorstore: /tmp/vectorstore.json