spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:./data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL_QUERY:false}

app:
  documentRoot: /Users/sergiotorreslozano/work/personal/invisor/data/documentation
  tepResources: classpath:tep/*
  paypalResources: classpath:paypal/*
  vectorstore: /Users/sergiotorreslozano/work/personal/invisor/data/vectorstore.json